services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD', 'pg_isready -U postgres' ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgres/data/pg_data
    networks:
      - mynetwork

  rabbit_recieve:
    build: .
    volumes:
      - .:/app
    command: [ "python", "rabbit/order_recieve.py", "new_orders" ]
    depends_on:
      - db
    networks:
      - mynetwork
    platform: linux/amd64

  rabbit_send:
    build: .
    volumes:
      - .:/app
    tty: true
    command: [ "python", "main.py" ]
    depends_on:
      - db
      - rabbit_recieve
    networks:
      - mynetwork
    platform: linux/amd64

networks:
  mynetwork:
    driver: bridge

volumes:
  pg_data: